{% set name = "sextractor" %}
{% set version = "2.28.0" %}

package:
  name: astromatic-source-extractor
  version: {{ version }}

source:
  url: https://github.com/astromatic/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 36f5afcdfe74cbf1904038a4def0166c1e1dde883e0030b87280dfbdfcd81969
  patches:
    - 0001-Search-lapacke-library.patch
    # Disable the compilation of ldactoasc.
    # See https://www.astromatic.net/forum/showthread.php?tid=902
    - 0002-Disable_ldactoasc_build.patch
    # Rename the executable and its man page
    - 0003-Rename_CLI_tool.patch
    # Needed for osx_arm64_
    - 0004-Fix-finite.patch

build:
  skip: true  # [win]
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - cfitsio
    - fftw
    - openblas
  run:
    - cfitsio
    - fftw
    - openblas

test:
  source_files:
    - tests
  commands:
    # These are simple existence tests.
    # The actual test suite is run via autotools in build.sh.
    - test -f ${CONDA_PREFIX}/bin/source-extractor
    - test $(readlink -f ${CONDA_PREFIX}/bin/sex) = ${CONDA_PREFIX}/bin/source-extractor  # [linux]

about:
  home: http://www.astromatic.net/software/sextractor
  license: GPL-3.0
  license_file: LICENSE
  summary: Extract catalogs of sources from astronomical images
  description: |
    SExtractor (Source-Extractor) is a program that builds a catalog of objects
    from an astronomical image. It is particularly oriented towards the
    reduction of large scale galaxy-survey data, but it also performs well on
    moderately crowded star fields.
  doc_url: https://sextractor.readthedocs.io/
  dev_url: https://github.com/astromatic/sextractor

extra:
  recipe-maintainers:
    - drbixx
    - teake
