build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
travis:
  secure:
    BINSTAR_TOKEN: 
      dW4FeTwW+VFh4eZ2F+O6e+UHXo4MJRHxJNVZgXTmQZJQE4H890Xa9Z4f5yTmIDIl/p2Fr2eb2+cuXU7Jn9KkfEjKwqmCFnOiT2spDsdRvPKAe0DHqUOz8iStesIyKjuu4SAdkPUJ5CszFaOgknoVXCTIqHPDhe5Er/4ghHSk65hbta/ZDZDo85zmcRhxSGQSwcIa14zksNRQe+cI4B/iFzVb2dZUFHy8vmI+Ze1RVnktZuBt5WDKCkF+CTqiBfFUzf2LXxFjwakU4zKaS3SCAxFmluThfAvQ18LdfMCZmcCuoYqr8eJAHhIV93Yz2E1cyYwjIAq7tIeNsAZ78CR9LC3iW2u99Ujepub7UMe8tckJZojvk6AO3dXntIr5Vl64+vuiUVWJRAfnvu1iUmX4SZlyxHLyyqIGrCnFTPSt/egqZVAkUnna+1eKfnYrkog0Zhj+pHV4XWW/DlnLODp2J8sg2QLgPoSk6hocgnVqL9E13oURGdmhpngsDovtXKYH83mfScJ7h2aA88URIYLKab9B/SDVBfGePIMrnNMwzx7EI3tH7XdWZMEptCgQava5MJ61H/qR+f/1GvQ63gwrpdDHiSS2+bOFNSCoOx8GlZwfPeXVdtyhLpmPL5mrPWObrL2whceCkZOQjrYSbazNfi4r7qQN6AKiGbMw7JdaDWY=
